model:
  base_learning_rate: 4.5e-06
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 8
    n_embed: 16384
    ddconfig:
      double_z: false
      z_channels: 8
      resolution: 256
      in_channels: 4
      out_ch: 4
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 4
        disc_start: 250001
        disc_weight: 0.75
        disc_num_layers: 2
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 14
    num_workers: 20
    wrap: true
    train:
      target: ldm.data.openimages.FullOpenImagesTrain
      params:
        size: 384
        crop_size: 256
    validation:
      target: ldm.data.openimages.FullOpenImagesValidation
      params:
        size: 384
        crop_size: 256
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 16
    train:
      target: taming.data.classegDataset.ClassegTrain
      params:
        size: 256
        dataset_num: 421
        dataset_name: large
        fold: 0
        mode: concat
    validation:
      target: taming.data.classegDataset.ClassegVal
      params:
        size: 256
        dataset_num: 421
        dataset_name: large
        fold: 0
        mode: concat
